### ISSUE TITLE
Rounded/Circled Avatars

### ISSUE THREAD

**Issue by TheCoward** [Retrospring/bugs#12]
Look, I know not everyone might like rounded aboatars, but maybe you could give people the option to put them on.

![rounded](https://a.pomf.se/kxnffa.png)
A basic rounded aboatar.

![rounded hover](https://a.pomf.se/shhakv.png)
Notice how it slightly grows upon hovering.

Also, I made mine so that all of those that are clickable will grow whenever they're :hover :active or :focus using the following code.
```css
.profile--image-avatar.hidden-xs:hover, .profile--image-avatar.hidden-xs:focus, .profile--image-avatar.hidden-xs:active {
  -webkit-transform: scale(1.1);
  transform: scale(1.1);
}
```
Bigger images should only be scaled by 1.05 though.
