### ISSUE TITLE
Navbar design suggestion

### ISSUE THREAD

**Issue by TheCoward** [Retrospring/bugs#16]
Yet another design suggestion from me! Yes, I know you don't like them that much :^)
Either way, that can stay as a userstyle thing, but I've been messing around with hover.css, and see, I made something with the navbar, which you can see on [this webm](http://a.pomf.se/fdkuuh.webm). Yes, I know it doesn't look that good on the profile picture, and I'm trying to get rid of the persistent shadow, but it looks fine, doesn't it? Remains to know if you'd like to implement it or not.

Here's teh code, and yes, it's that fucking hardcoded:
```css
/* Trying something */

.nav>li {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    -moz-osx-font-smoothing: grayscale;
    position: relative;
    overflow: hidden;
}
.nav>li:before {
    content: "";
    position: absolute;
    z-index: -1;
    left: 0;
    right: 0;
    bottom: 0;
    background: #fff;
    height: 4px;
    -webkit-transform: translateY(4px);
    transform: translateY(4px);
    -webkit-transition-property: transform;
    transition-property: transform;
    -webkit-transition-duration: 0.3s;
    transition-duration: 0.3s;
    -webkit-transition-timing-function: ease-out;
    transition-timing-function: ease-out;
}
.nav>li:hover:before,
.nav>li:focus:before,
.nav>li:active:before {
    -webkit-transform: translateY(0);
    transform: translateY(0);
}
.navbar-inverse .btn-link:hover,
.navbar-inverse .btn-link:focus {
    color: #fff;
}
.navbar-inverse .navbar-nav>li>a:hover,
.navbar-inverse .navbar-nav>li>a:focus {
    color: #fff;
}
.navbar-nav>li>a {
    color: #fff;
}
```
Apparently it also breaks the dropdown, but guess I only need to remove the :focus.
![crap](https://a.pomf.se/zwstsn.png)
