### ISSUE TITLE
Locale: ability to specify sexuality of a name when it's used in various contexts

### ISSUE THREAD

**Issue by TheHowl** [Retrospring/bugs#75]
As you might already know, latin-derivated languages love to make things extremely overcomplicated. An example is when a noun is male or female, all articles and adjectives change. For example:

> Really report this question?
> _Vuoi davvero segnalare quest**a** domanda?_
> Really report this user?
> _Vuoi davvero segnalare quest**o** utente?_

So, should we do this in order to be able to make sentences that have sense in the locale?

```
        title: "Vuoi davvero eliminare quest%{type}?"
```

and then in the types do something like `a domanda` or `o utente` or it's better to make a function for it?

**Comment by pixeldesu** [comment]
Is there no way to make it pretty much neutral, or as neutral as possible?

**Comment by TheHowl** [comment]
Although in that example at the very least I can do some workarounds (such as `Vuoi davvero eliminare tale %{type}?`), I don't think it's possible in every case.

**Comment by yukimono** [comment]
[we need to implement this](http://stackoverflow.com/a/5004629)

**Comment by yukimono** [comment]
It's worth mentioning all western european languages, some asian languages, and classical latin all have at least some gendered nouns, worst case is french which has almost no neutral nouns.

**Comment by yukimono** [comment]
an easy alternative to this is to make the report key like
```yml
report:
  _: "Do you really want to report this #{type}?"
  question: "Do you really want to report this question?"
  answer: "Do you really want to report this answer?"
```
and access it as
```rb
def typed
